### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by SaddamBInSyed** [JunweiLiang/social-distancing-prediction#2]
@JunweiLiang 
Thanks for your work.

I have carefully followed the instructions and when i run the code on my ubuntu 18.04 (cpu only) machine then i am getting the below exception.

`/home/deeplearning/projects/social-distancing-prediction/venv/bin/python /home/deeplearning/projects/social-distancing-prediction/code/inference/main.py
/home/deeplearning/projects/social-distancing-prediction
Loading obj model...
obj model loaded.
Loading scene seg model...
scene seg model loaded.
Loading person appearance model...
person appearance model loaded.
Loading prediction model...
prediction model loaded.
  0%|          | 0/1 [00:00<?, ?it/s]1. Getting video frames...
	Done.
2. Object detection & tracking...
  0%|          | 0/1 [00:19<?, ?it/s]
  0%|          | 0/75 [00:02<?, ?it/s]
  0%|          | 0/1 [00:21<?, ?it/s]
Traceback (most recent call last):
  File "/home/deeplearning/projects/social-distancing-prediction/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/deeplearning/projects/social-distancing-prediction/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/deeplearning/projects/social-distancing-prediction/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
	 [[{{node model_0/pool0/max_pooling2d/MaxPool}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deeplearning/projects/social-distancing-prediction/code/inference/main.py", line 446, in <module>
    feed_dict=feed_dict)
  File "/home/deeplearning/projects/social-distancing-prediction/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/deeplearning/projects/social-distancing-prediction/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/deeplearning/projects/social-distancing-prediction/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/deeplearning/projects/social-distancing-prediction/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
	 [[node model_0/pool0/max_pooling2d/MaxPool (defined at /venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'model_0/pool0/max_pooling2d/MaxPool':
  File "/code/inference/main.py", line 257, in <module>
    gpuid=args.gpuid)
  File "/code/inference/Object_Detection_Tracking/models.py", line 98, in get_model
    add_mask=config.add_mask)
  File "/code/inference/Object_Detection_Tracking/models.py", line 193, in __init__
    return_elements=None
  File "/venv/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 517, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3561, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3561, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3451, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

Process finished with exit code 1
`

please advise how to resolve this

**Comment by JunweiLiang** [comment]
Currently the code only supports Tensorflow-GPU.

**Comment by SaddamBInSyed** [comment]
Thanks for your response.
 
I Would like to know whether this code will run on Jetson nano ?

Thanks.

**Comment by JunweiLiang** [comment]
Not sure. I guess if you can install Tensorflow-GPU then it should work. Let me know if it works.

**Comment by SaddamBInSyed** [comment]
@JunweiLiang 
thanks for the response 

I have tried the code on my jetson nano ( tf 1.15.0 )

I am getting the below errors


`Loading obj model...
obj model loaded.
Loading scene seg model...
scene seg model loaded.
Loading person appearance model...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code/inference/main.py", line 290, in <module>
    person_appearance_config, sess, gpuid=args.gpuid)
  File "/home/deeplearning/project/social-distancing-prediction/code/inference/inf_utils.py", line 358, in get_person_appearance_model
    load_model_weights(model_config.model_path, sess)
  File "/home/deeplearning/project/social-distancing-prediction/code/inference/inf_utils.py", line 418, in load_model_weights
    saver.restore(sess, loadpath)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "code/inference/main.py", line 290, in <module>
    person_appearance_config, sess, gpuid=args.gpuid)
  File "/home/deeplearning/project/social-distancing-prediction/code/inference/inf_utils.py", line 358, in get_person_appearance_model
    load_model_weights(model_config.model_path, sess)
  File "/home/deeplearning/project/social-distancing-prediction/code/inference/inf_utils.py", line 411, in load_model_weights
    saver = tf.train.Saver(restore_vars, max_to_keep=5)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
`


please advise

**Comment by JunweiLiang** [comment]
> Dst tensor is not initialized.

This is usually due to insufficient GPU memory. I have tested the code on RTX 2060 with 6GB GPU memory and GTX 1080 TI with 11GB GPU memory.

**Comment by SaddamBInSyed** [comment]
thanks

seems no way to test.

but once again thanks.
