### ISSUE TITLE
The name 'model_0/image:0' refers to a Tensor which does not exist. The operation, 'model_0/image', does not exist in the graph.

### ISSUE THREAD

**Issue by BeardyMan37** [JunweiLiang/social-distancing-prediction#6]
When I run the code using the following command,
`python code/inference/main.py test/test_videos.lst test/output --pred_vis_path test/visualization
`
the code runs into an error saying,
`Loading obj model...
Traceback (most recent call last):
  File "code/inference/main.py", line 253, in <module>
    obj_model = get_object_detection_model(argparse.Namespace(
  File "/home/rakib/Desktop/Job Project/Codes/Independent projects/social-distancing-prediction/code/inference/Object_Detection_Tracking/models.py", line 97, in get_model
    model = Mask_RCNN_FPN_frozen(config.load_from, gpuid,
  File "/home/rakib/Desktop/Job Project/Codes/Independent projects/social-distancing-prediction/code/inference/Object_Detection_Tracking/models.py", line 198, in __init__
    self.image = self.graph.get_tensor_by_name("%s/image:0" % self.var_prefix)
  File "/home/rakib/.virtualenvs/dl4cv/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 3783, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/rakib/.virtualenvs/dl4cv/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 3607, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/rakib/.virtualenvs/dl4cv/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 3647, in _as_graph_element_locked
    raise KeyError("The name %s refers to a Tensor which does not "
KeyError: "The name 'model_0/image:0' refers to a Tensor which does not exist. The operation, 'model_0/image', does not exist in the graph."`

I know this project is wrapped up. But any sort of help will be appreciated.

**Comment by JunweiLiang** [comment]
This means that the object detection model is not loaded correctly. Did you download the models using the provided script and what is your TensorFlow version?

**Comment by BeardyMan37** [comment]
I downloaded the models using the provided script and then ran the command, only to find that the previously installed version of TensorFlow(r2.2) wasn't supported. Then I compiled Tensorflow from scratch; version r1.15.3. Downloading the models from the script once again right now.

**Comment by BeardyMan37** [comment]
When downloading the models, I encounter this problem first things first:
`Resolving aladdin-eax.inf.cs.cmu.edu (aladdin-eax.inf.cs.cmu.edu)... 128.2.204.83
Connecting to aladdin-eax.inf.cs.cmu.edu (aladdin-eax.inf.cs.cmu.edu)|128.2.204.83|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-01 04:39:16 ERROR 404: Not Found.
`

**Comment by JunweiLiang** [comment]
The link is fixed now. Please try again.

**Comment by BeardyMan37** [comment]
I tried and the link worked. The last question, will I be able to run it in a machine with only a CPU? I seemed to have run into some problem with the data formatting of "NHWC" and "NCHW", that MaxPoolingOp supports only NHWC. Will appreciate some clarification.

**Comment by JunweiLiang** [comment]
I haven't tested with CPU-only machines.

**Comment by BeardyMan37** [comment]
Okay. You can close the issue. You've done some amazing work btw. Instant fan here.

**Comment by JunweiLiang** [comment]
Thanks bud.
