### ISSUE TITLE
Problem in step 2: Run inferencing

### ISSUE THREAD

**Issue by Katreenlooper** [JunweiLiang/social-distancing-prediction#7]
Hey,
I run the following command: 
python code/inference/main.py test/test_videos.lst test/output --pred_vis_path test/visualization
but the process is not completed for some reasons.. The visualization directory is not created as well in the output folder.
I got the following message in the terminal:

FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Loading obj model...
obj model loaded.
Loading scene seg model...
scene seg model loaded.
Loading person appearance model...
person appearance model loaded.
Loading prediction model...
prediction model loaded.
1. Getting video frames...                                                      
        Done.                                                                   
2. Object detection & tracking...                                               
  0%|                                                    | 0/75 [00:01<?, ?it/s]
  0%|                                                     | 0/1 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "code/inference/main.py", line 444, in <module>
    feed_dict=feed_dict)
  File "/home/nadim/anaconda3/envs/myenv/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/nadim/anaconda3/envs/myenv/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/nadim/anaconda3/envs/myenv/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/nadim/anaconda3/envs/myenv/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
	 [[node model_0/pool0/max_pooling2d/MaxPool (defined at /home/nadim/anaconda3/envs/myenv/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for u'model_0/pool0/max_pooling2d/MaxPool':
  File "code/inference/main.py", line 255, in <module>
    gpuid=args.gpuid)
  File "/home/nadim/speed/Mine/social-distancing-prediction/code/inference/Object_Detection_Tracking/models.py", line 98, in get_model
    add_mask=config.add_mask)
  File "/home/nadim/speed/Mine/social-distancing-prediction/code/inference/Object_Detection_Tracking/models.py", line 193, in __init__
    return_elements=None
  File "/home/nadim/anaconda3/envs/myenv/lib/python2.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/nadim/anaconda3/envs/myenv/lib/python2.7/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/nadim/anaconda3/envs/myenv/lib/python2.7/site-packages/tensorflow_core/python/framework/importer.py", line 517, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/home/nadim/anaconda3/envs/myenv/lib/python2.7/site-packages/tensorflow_core/python/framework/importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/home/nadim/anaconda3/envs/myenv/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py", line 3561, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/nadim/anaconda3/envs/myenv/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py", line 3451, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/home/nadim/anaconda3/envs/myenv/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

Thank you for your help.

**Comment by JunweiLiang** [comment]
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
```
You need to run it with Tensorflow-GPU.

**Comment by Mzunoven** [comment]
> ```
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
> ```
> 
> You need to run it with Tensorflow-GPU.

Hi, I've met exactly the same issue and I'm using tensorflow-gpu==1.15.3(however, I uninstalled tensorflow to make sure that I'm using the tensorflow GPU version), is there any other possible solution for this problem or did I made some thing wrong?

**Comment by JunweiLiang** [comment]
After installing tensorflow-gpu, you can try [this](https://www.tensorflow.org/guide/gpu#setup) to make sure python uses the gpu version
